
//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------


namespace BlogCompiler.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Category
{

    public Category()
    {

        this.Post = new HashSet<Post>();

    }


    public string CATEGORY_CODE { get; set; }

    public string CATEGORY_NAME { get; set; }

    public string URL { get; set; }

    public string SUBDIR { get; set; }

    public bool ISHOME { get; set; }

    public bool ISDELETED { get; set; }

    public int SEQUENCE { get; set; }



    public virtual ICollection<Post> Post { get; set; }

}

}
